.PHONY: all clean
all: lib/sqlite3_new.c lib/ezsqlite_stubs.c
	riscv64-unknown-linux-gnu-gcc -I/home/sai/.opam/4.07.0/riscv-sysroot/lib/ocaml -c lib/sqlite3_new.c
	riscv64-unknown-linux-gnu-gcc -I/home/sai/.opam/4.07.0/riscv-sysroot/lib/ocaml -c lib/ezsqlite_stubs.c
	riscv64-unknown-linux-gnu-ar rcs libezsqlite_stubs.a ezsqlite_stubs.o sqlite3_new.o
	riscv64-unknown-linux-gnu-ranlib libezsqlite_stubs.a 

clean:
	rm *.o
	rm *.a
# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10
#build.make
# compile ASM with /home/sai/Shakti_TEE_Practical/bin/riscv64-unknown-elf-gcc
# compile CXX with /home/sai/Shakti_TEE_Practical/bin/riscv64-unknown-elf-g++
# ASM_FLAGS =  

# ASM_DEFINES = -DHTIF

# ASM_INCLUDES = -I/home/sai/.opam/4.07.0/.opam-switch/build/ocaml-boot-riscv.0.1/include -I/home/sai/.opam/4.07.0/.opam-switch/build/ocaml-boot-riscv.0.1/include/ocaml-boot-riscv -I/home/sai/.opam/4.07.0/.opam-switch/build/ocaml-boot-riscv.0.1/src 

# CXX_FLAGS = -mcmodel=medany  

# CXX_DEFINES = -DHTIF

# CXX_INCLUDES = -I/home/sai/.opam/4.07.0/.opam-switch/build/ocaml-boot-riscv.0.1/include -I/home/sai/.opam/4.07.0/.opam-switch/build/ocaml-boot-riscv.0.1/include/ocaml-boot-riscv -I/home/sai/.opam/4.07.0/.opam-switch/build/ocaml-boot-riscv.0.1/src 

