.PHONY: all
all: lib/sqlite3_new.c lib/ezsqlite_stubs.c
	riscv64-unknown-elf-gcc  -o lib/sqlite3_new.o -c lib/sqlite3_new.c
	riscv64-unknown-elf-gcc  -o lib/ezsqlite_stubs.o -c lib/ezsqlite_stubs.c
	riscv64-unknown-elf-ar qc libezsqlite_stubs.a  lib/sqlite3_new.o lib/ezsqlite_stubs.o
	riscv64-unknown-elf-ranlib libezsqlite_stubs.a 

# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10
#build.make
# compile ASM with /home/sai/Shakti_TEE_Practical/bin/riscv64-unknown-elf-gcc
# compile CXX with /home/sai/Shakti_TEE_Practical/bin/riscv64-unknown-elf-g++
# ASM_FLAGS =  

# ASM_DEFINES = -DHTIF

# ASM_INCLUDES = -I/home/sai/.opam/4.07.0/.opam-switch/build/ocaml-boot-riscv.0.1/include -I/home/sai/.opam/4.07.0/.opam-switch/build/ocaml-boot-riscv.0.1/include/ocaml-boot-riscv -I/home/sai/.opam/4.07.0/.opam-switch/build/ocaml-boot-riscv.0.1/src 

# CXX_FLAGS = -mcmodel=medany  

# CXX_DEFINES = -DHTIF

# CXX_INCLUDES = -I/home/sai/.opam/4.07.0/.opam-switch/build/ocaml-boot-riscv.0.1/include -I/home/sai/.opam/4.07.0/.opam-switch/build/ocaml-boot-riscv.0.1/include/ocaml-boot-riscv -I/home/sai/.opam/4.07.0/.opam-switch/build/ocaml-boot-riscv.0.1/src 

