#define NDEBUG 1
#define SQLITE_DEFAULT_MEMSTATUS 0
#define SQLITE_ENABLE_COLUMN_METADATA 1
#define SQLITE_DEFAULT_FOREIGN_KEYS 1
#define SQLITE_DEFAULT_AUTO_VACUUM 0
// #define SQLITE_ENABLE_JSON1 0
// #define SQLITE_ENABLE_RTREE 0
// #define SQLITE_ENABLE_SESSION 1
// #define SQLITE_MAX_ATTACHED 5
#define SQLITE_THREADSAFE 0
// #define SQLITE_OMIT_LOAD_EXTENSION 1
#define SQLITE_UNTESTABLE 1
#define SQLITE_OMIT_INCRBLOB 1 
// #define SQLITE_OMIT_AUTOVACUUM 1
#define SQLITE_OMIT_FLOATING_POINT 1
#define SQLITE_OMIT_UTF16 1
// #define SQLITE_AMALGAMATION 1
#define SQLITE_ASCII 1
// #define SQLITE_DISABLE_DIRSYNC 1
// #define SQLITE_DISABLE_FTS3_UNICODE 1
// #define SQLITE_DISABLE_LFS 1
// #define SQLITE_DISABLE_PAGECACHE_OVERFLOW_STATS 1
// #define SQLITE_ENABLE_LOAD_EXTENSION 1
// #define SQLITE_MUTEX_OMIT 1
// #define SQLITE_NO_SYNC 1
#define SQLITE_OMIT_BLOB_LITERAL 1
// #define SQLITE_OMIT_FLOATING_POINT 1
// #define SQLITE_OMIT_INCRBLOB 1
#define SQLITE_OMIT_TCL_VARIABLE 1
#define SQLITE_OMIT_TRACE 1
#define SQLITE_OMIT_TEST_CONTROL 1
// #define SQLITE_OMIT_WAL 1 
#define SQLITE_RTREE_INT_ONLY 1
#define SQLITE_OMIT_DATETIME_FUNCS 1
#define SQLITE_OS_OTHER 1 
// #define SQLITE_GANESHA_OS 1 
#define SQLITE_OMIT_AUTHORIZATION 1
#define SQLITE_OMIT_LOCALTIME 1
#define SQLITE_OMIT_EXPLAIN 1
// #define SQLITE_OMIT_COMPOUND_SELECT 1
// #define SQLITE_OMIT_BTREECOUNT 1
#define SQLITE_OMIT_PARSER_TRACE 1
#define SQLITE_PERFORMANCE_TRACE 0
#define SQLITE_ENABLE_DESERIALIZE 1
// #define SQLITE_OMIT_VIEW 1
#define SQLITE_SYSTEM_MALLOC 1
// #define SQLITE_OMIT_DISKIO 1

// #ifndef SQLITE_OMIT_ALTERTABLE
// #ifndef SQLITE_OMIT_AUTHORIZATION
// #ifndef SQLITE_OMIT_VIRTUALTABLE
// #ifndef SQLITE_OMIT_VIEW
// #ifndef SQLITE_OMIT_FOREIGN_KEY
// #ifndef SQLITE_OMIT_AUTOINCREMENT
// #ifndef SQLITE_OMIT_FOREIGN_KEY
// #ifndef SQLITE_OMIT_TRIGGER
#define SQLITE_OMIT_ANALYZE 1 // sairam
// #ifndef SQLITE_OMIT_ATTACH
// #ifndef SQLITE_OMIT_PAGER_PRAGMAS
// #ifndef SQLITE_OMIT_UPSERT
// #ifndef SQLITE_OMIT_VACUUM
// #ifndef SQLITE_OMIT_INCRBLOB
// #ifndef SQLITE_OMIT_AUTOVACUUM
// SQLITE_OMIT_WAL
// SQLITE_OMIT_QUICKBALANCE
// #ifndef SQLITE_OMIT_BTREECOUNT
// #ifndef SQLITE_OMIT_INTEGRITY_CHECK
// SQLITE_OMIT_SUBQUERY
// #ifndef SQLITE_OMIT_TRUNCATE_OPTIMIZATION
// #ifndef SQLITE_OMIT_DATETIME_FUNCS

// Look into ctime.c

